server:
  port: 8094

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  mail:
    username: ${MAIL}
    username2: ${MAIL_2}
    password: ${MAIL_PASSWORD} #app password
    host: ${SMTP_GMAIL}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue
  queueEmail: email-queue
  emailKey: email-key

