server:
  port: 8093
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: movie-service
  data:
    mongodb:
      host: localhost
      port: 29000
      username: "java5user"
      password: "root"
      database: moviedb